airbnb-fe/package.json, airbnb-fe/src/App.js, airbnb-fe/src/auth_config.json, airbnb-fe/src/components/ExternalApi.js, airbnb-fe/src/components/NavBar.js, airbnb-fe/src/index.js
=> Auth0 jwt implementation

airbnb-fe/src/App.js, airbnb-fe/src/components/Calendar.js, airbnb-fe/src/components/Day.js, airbnb-fe/src/components/Week.js
=> Creates calendar component

airbnb-fe/src/App.js, airbnb-fe/src/components/Profile.js, airbnb-fe/src/components/listing/Listing.js, airbnb-fe/src/components/listing/ResultBox.js, airbnb-fe/src/components/listing/Text.js
=> Some work on listing view

airbnb-fe/src/App.js, airbnb-fe/src/components/calendar/Calendar.js, airbnb-fe/src/components/calendar/Day.js, airbnb-fe/src/components/listing/DayInfo.js, airbnb-fe/src/components/listing/Listing.js, airbnb-fe/src/components/listing/MessageBox.js, airbnb-fe/src/components/listing/ResultBox.js, airbnb-fe/src/components/listing/Text.js
=> Login styling

airbnb-fe/src/components/calendar/Day.js, netlify.toml
=> Added netlify.toml

airbnb-fe/.gitignore, netlify.toml
=> netlify toml and gitignore updates

airbnb-fe/package-lock.json, airbnb-fe/src/components/landing/Quadrant4.js
=> Removed carousel from quadrant4

airbnb-fe/src/index.js
=> Swapped provider and context in index.js

airbnb-fe/src/auth_config.json, airbnb-fe/src/components/NavBar.js, airbnb-fe/src/index.js, airbnb-fe/src/react-auth0-wrapper.js
=> Redirects to dash after login, but choppy landing flash

airbnb-fe/package-lock.json, airbnb-fe/package.json, airbnb-fe/src/App.js, airbnb-fe/src/components/NavBar.js, airbnb-fe/src/components/confirmation/ResultBox.js, airbnb-fe/src/components/dashboard/Dashboard.js, airbnb-fe/src/components/landing/Header.js, airbnb-fe/src/components/search/SearchBar.js, airbnb-fe/src/index.js, airbnb-fe/src/store/actions/index.js, airbnb-fe/src/store/reducers/index.js
=> Routed demo and backend

airbnb-fe/src/store/actions/index.js
Co-authored-by: Vlad <vladmog@gmail.com>
=> changed urls for axios calls to deployed heroku url,

airbnb-fe/public/index.html
=> google analytics implementation

airbnb-fe/package-lock.json, airbnb-fe/src/components/search/SearchBar.js
=> added Ridley's parseIdFromUrl f(x)

airbnb-fe/package-lock.json, airbnb-fe/package.json, airbnb-fe/src/App.js, airbnb-fe/src/components/charts/Chart.js, airbnb-fe/src/components/charts/Chart2.js, airbnb-fe/src/components/charts/Chart3.js, airbnb-fe/src/components/listing/Listing.js, airbnb-fe/src/components/listing2/Listing2.js, airbnb-fe/src/components/listing2/Quadrant1.js, airbnb-fe/src/components/listing2/Quadrant2.js, airbnb-fe/src/components/listing2/Quadrant3.js, airbnb-fe/src/components/listing2/Quadrant4.js
=> new listings page with static charts

airbnb-fe/package-lock.json, airbnb-fe/package.json, airbnb-fe/src/components/dashboard/Dashboard.js, airbnb-fe/src/components/dashboard/Listing.js, airbnb-fe/src/components/dashboard/Listings.js, airbnb-fe/src/components/dashboard/dashboard-tests/Dashboard.test.js, airbnb-fe/src/components/dashboard/dashboard-tests/Header.test.js, airbnb-fe/src/components/dashboard/dashboard-tests/Listing.test.js, airbnb-fe/src/components/dashboard/dashboard-tests/Listings.test.js, airbnb-fe/src/components/search/SearchBar.js, airbnb-fe/src/components/search/search-tests/SearchBar.test.js, airbnb-fe/src/store/actions/index.js
Added 5 tests, 2 of which are failing. Resolved rendering issue with Listings component.
Listings render.
=> Snapshot tests

airbnb-fe/src/components/dashboard/Dashboard.js, airbnb-fe/src/components/dashboard/Listing.js, airbnb-fe/src/components/dashboard/Listings.js, airbnb-fe/src/store/actions/index.js, airbnb-fe/src/store/reducers/index.js
=> Listing crud

airbnb-fe/src/App.js, airbnb-fe/src/components/Mediator.js, airbnb-fe/src/components/NavBar.js, airbnb-fe/src/components/confirmation/SecondHalf.js, airbnb-fe/src/components/dashboard/Dashboard.js, airbnb-fe/src/components/dashboard/Listing.js, airbnb-fe/src/components/listing2/Listing2.js, airbnb-fe/src/components/search/SearchBar.js, airbnb-fe/src/components/search/SearchBarNav.js, airbnb-fe/src/store/actions/index.js
=> NavBar now dynamic

airbnb-fe/src/App.js, airbnb-fe/src/components/charts/Chart2.js, airbnb-fe/src/components/confirmation/ResultBox.js, airbnb-fe/src/components/listing2/Listing2.js, airbnb-fe/src/components/listing2/Quadrant2.js, airbnb-fe/src/store/actions/index.js, airbnb-fe/src/store/reducers/index.js
=> New listing page implemented

airbnb-fe/src/store/actions/index.js
=> changed to heroku BE routes

airbnb-fe/src/store/actions/index.js, airbnb-fe/src/store/reducers/index.js
=> added amenities endpoint

airbnb-fe/src/components/listing2/Listing2.js, airbnb-fe/src/components/listing2/Quadrant2.js, airbnb-fe/src/components/listing2/Quadrant3.js, airbnb-fe/src/components/listing2/Quadrant4.js, airbnb-fe/src/store/actions/index.js
=> Adding blurred sections for demo

airbnb-fe/src/components/listing2/Quadrant3.js
=> Quadrant3 of listing2 now dynamic

airbnb-fe/src/components/charts/Chart2.js, airbnb-fe/src/components/charts/Chart3.js, airbnb-fe/src/components/listing2/Listing2.js, airbnb-fe/src/components/listing2/Quadrant3.js, airbnb-fe/src/components/listing2/Quadrant4.js, airbnb-fe/src/store/actions/index.js
=> all data dynamic, removed cors-anywhere from some endpoints

airbnb-fe/src/components/NavBar.js, airbnb-fe/src/components/charts/Chart2.js, airbnb-fe/src/components/charts/Chart3.js, airbnb-fe/src/components/listing2/Listing2.js, airbnb-fe/src/components/listing2/Quadrant3.js
=> Added loaders to charts, profile img is now dynamic

airbnb-fe/src/components/NavBar.js, airbnb-fe/src/components/charts/Chart2.js, airbnb-fe/src/components/dashboard/Listing.js, airbnb-fe/src/components/listing/Text.js, airbnb-fe/src/components/search/SearchBar.js, airbnb-fe/src/components/search/SearchBarNav.js
=> Visual refinement to navbar

README.md
=> Added analytics to README

airbnb-fe/src/components/confirmation/ResultBox.js, airbnb-fe/src/store/actions/index.js, airbnb-fe/src/store/reducers/index.js
=> added ability to clear searchResult

airbnb-fe/src/components/NavBar.js, airbnb-fe/src/components/confirmation/ResultBox.js, airbnb-fe/src/components/listing2/Quadrant1.js
=> added ability to clear searchResult by clicking on the home logo

airbnb-fe/src/components/charts/Chart2.js, airbnb-fe/src/components/charts/Chart3.js, airbnb-fe/src/components/listing2/Quadrant3.js, airbnb-fe/src/components/listing2/Quadrant4.js
=> Added spacing to Q3 in listing2

airbnb-fe/src/components/confirmation/ResultBox.js, airbnb-fe/src/components/confirmation/Text.js
=> saved our lives
